server:
    port: 8080

logging:
    level:
        com.weChat: DEBUG

spring:
    profiles:
      active: development
    datasource:
        name: test
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20



---
spring:
  profiles: development

  datasource:
    url: jdbc:mysql://localhost:3306/we_chat?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: wxyadmin

  thymeleaf:
    cache: false


---
spring:
  profiles: production

  datasource:
    url: jdbc:mysql://192.168.0.100:3306/bebase?useUnicode=true&characterEncoding=utf8
    username: root
    password: wxyadmin